User.create(handle: '@' + 'godard')
User.create(handle: '@' + 'cardigan')
User.create(handle: '@' + 'church-key')
User.create(handle: '@' + 'XOXO')
User.create(handle: '@' + 'gluten-free')

Tweet.create(content: 'Williamsburg gastropub four loko, retro Odd Future occupy small batch cliche', user_id: rand(1..5))
Tweet.create(content: 'freegan PBR stumptown fashion axe leggings drinking vinegar 3 wolf moon', user_id: rand(1..5))
Tweet.create(content: 'Cronut Odd Future meggings, dreamcatcher messenger bag keffiyeh twee cornhole synth Portland wayfarers heirloom pour-over', user_id: rand(1..5))
Tweet.create(content: 'Next level street art paleo Portland stumptown, lumbersexual High Life PBR trust fund slow-carb Helvetica', user_id: rand(1..5))
Tweet.create(content: 'meditation readymade fixie freegan. PBR&B shabby chic mustache asymmetrical flannel', user_id: rand(1..5))
Tweet.create(content: 'Asymmetrical try-hard artisan, literally typewriter kale chips lomo', user_id: rand(1..5))
Tweet.create(content: 'Normcore artisan bitters, scenester salvia wolf polaroid leggings next level whatever PBR&B 90\'s fap brunch ennui', user_id: rand(1..5))
Tweet.create(content: 'Shabby chic listicle yr Bushwick. Pitchfork vegan fingerstache, bespoke synth selvage meggings aesthetic you probably haven\'t heard of them roof party. ', user_id: rand(1..5))
Tweet.create(content: 'Schlitz Pitchfork next level cred. Messenger bag next level four loko, try-hard flexitarian 3 wolf moon whatever chambray Tumblr VHS cronut', user_id: rand(1..5))
Tweet.create(content: 'Fap mixtape lomo, letterpress hashtag actually VHS taxidermy Godard meditation', user_id: rand(1..5))
